openapi: "3.1.1"
info:
  title: redgiant
  version: "0.0.1"

paths:
  /api/about:
    get:
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/About"
  /api/state:
    get:
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/State"
  /api/devices:
    get:
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Device"
  /api/live-data/{deviceID}:
    get:
      parameters:
        - in: path
          name: deviceID
          schema:
            type: integer
          required: true
        - in: query
          name: lang
          schema:
            type: string
            enum:
              - ch_CN
              - en_US
              - de_DE
              - nl_NL
              - pl_PL
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Datapoint"

components:
  schemas:
    About:
      properties:
        serialNumber:
          type: string
        version:
          type: string
        softwareVersion:
          type: string
        buildVersion:
          type: string
    State:
      properties:
        totalFaults:
          type: integer
        totalAlarms:
          type: integer
        wirelessConnection:
          type: boolean
        wifiConnection:
          type: boolean
        ethernet1Connection:
          type: boolean
        ethernet2Connection:
          type: boolean
        cloudConnection:
          type: boolean
    Device:
      properties:
        id:
          type: integer
        code:
          type: integer
        type:
          type: integer
        protocol:
          type: integer
        serialNumber:
          type: string
        name:
          type: string
        model:
          type: string
        special:
          type: string
        invType:
          type: integer
        physicalAddress:
          type: integer
        logicalAddress:
          type: integer
        linkStatus:
          type: integer
        initStatus:
          type: integer
    Datapoint:
      properties:
        i18nCode:
          type: string
        name:
          type: string
        value:
          type: string
        unit:
          type: string
